### ISSUE TITLE
2FA support

### ISSUE THREAD

**Issue by j-d** [chrisledet/rebasebot#11]
Hi, 

I tried to install this and I got this error:

```
2019/06/18 04:25:31 github.find_pr.started
2019/06/18 04:25:31 github.find_pr.failed status:  401
2019/06/18 04:25:31 git.fetch.started: /tmp/rebasebot
2019/06/18 04:25:31 git.fetch.failed: /tmp/rebasebot exit status 128
2019/06/18 04:25:31 git.remote.prune.started: /tmp/rebasebot
2019/06/18 04:25:31 git.remote.prune.failed: /tmp/rebasebot exit status 128
2019/06/18 04:25:31 github.pr.comments.create.started
2019/06/18 04:25:31 github.pr.comments.create.failed status: 401, msg: Must specify two-factor authentication OTP code.
```

I don't think it is currently possible to configure the Oauth token? 

Cheers, J

**Comment by chrisledet** [comment]
Hi @j-d, you should just be able to configure your Oauth token with the `GITHUB_PASSWORD` environment variable.

**Comment by chrisledet** [comment]
2FA on the otherwise is different and not currently supported.

**Comment by chrisledet** [comment]
I'm curious about your setup: are you creating a dedicated GitHub account for the bot with 2FA enabled?

**Comment by j-d** [comment]
@chrisledet I've added the bot user to the organisation, but the organisation requires 2FA for all its users. I will try to use the Oauth token as the password now

**Comment by j-d** [comment]
Yes, that worked. Thanks! 👍
