### ISSUE TITLE
Wrong repo on push

### ISSUE THREAD

**Issue by emilevauge** [chrisledet/rebasebot#4]
Hi,

I would like to use rebasebot on a project, but it seems that rebasebot is (maybe?) trying to push the code on the forked repo instead of the origin repo.
I'm using the docker image:

`sudo docker run --restart=always -d --name rebasebot -e "PORT=8080" -e "GITHUB_USERNAME=user" -e "GITHUB_PASSWORD=password" -e "SECRET=secret" -p 8080 chrisledet/rebasebot`

I have added the github rebasebot user to the project.

And I'm getting errors:

```
2016/01/11 14:18:12 git.push.started: /tmp/dylanmei/traefik marathon_uses_port_from_label
2016/01/11 14:18:13 git.push.failed: /tmp/dylanmei/traefik exit status 128
2016/01/11 14:18:13 github.pr.comments.create.started
2016/01/11 14:18:14 github.pr.comments.create.failed status: 404, msg: Not Found 
```

Did I miss something?

**Comment by chrisledet** [comment]
Definitely not intended behavior. We'll get it fixed up.

**Comment by chrisledet** [comment]
Hey, I just reviewed your issue. That's actually the intended behavior. rebasebot was built for managing hundreds of branches on large code bases. I didn't design it for forked repositories however I'm open to supporting more use cases if it's useful. What were you looking for?

**Comment by emilevauge** [comment]
I'm the maintainer of a repo. If someone wants to create a PR, he has to fork the project, and has to create his PR from his forked project.
Should work no ?
But I'm not sure that errors come from that issue, I'm just assuming, because logs lacks a bit of verbosity ;)

**Comment by chrisledet** [comment]
> I'm the maintainer of a repo. If someone wants to create a PR, he has to fork the project, and has to create his PR from his forked project.

Your rebasebot instance is not authorized to access other people's repositories based on the credentials you provided. They would either need to give the bot access to it's repositories or set up their own instance. I know, not ideal.

> But I'm not sure that errors come from that issue, I'm just assuming, because logs lacks a bit of verbosity ;)

[Agreed](https://github.com/chrisledet/rebasebot/issues/3).

**Comment by emilevauge** [comment]
OK, thanks ;)
