### ISSUE TITLE
implement `rebased` status check

### ISSUE THREAD

**Issue by Guria** [chrisledet/rebasebot#6]
https://developer.github.com/v3/repos/statuses/

would be great to make status check that pr is rebased. it would allow to enforce requirement to prevent merging not rebased pr

**Comment by chrisledet** [comment]
I'd like to hear some specific use cases for it.

**Comment by Guria** [comment]
github allow to prevent merging to branch if some list of checks hasn't passed. it already helps to prevent pushing code that doesn't successfuly passed tests on CI and with decreased coverage. would be great to check that pr branch is based on master, otherwise github will disable merge button and drop any attempt to push such commits directly from cli

**Comment by chrisledet** [comment]
GitHub now has this feature built-in to its product in the Branches section. "Require branches to be up-to-date before merging" option ensures that the branch is tested with the latest code on the base branch.

https://help.github.com/articles/enabling-required-status-checks
